### ISSUE TITLE
Reissueing a token after the current one has expired

### ISSUE THREAD

**Issue by Dindaleon** [dwyl/hapi-auth-jwt2#118]
Hello,

I would like to know how I can catch the 401 "token expired" response in order to reissue a new token.

**EDIT** is it ok to set the ignoreExpiration option to true and then verify the expiration time inside the `validateFunc` function?

**Comment by nelsonic** [comment]
Hi @Dindaleon, yes, its *fine* to `options.ignoreExpiration = true` and then do your own expiration validation inside your `validateFunc`. :+1: 
Let us know if you need any help with this. 
Thanks for trying the plugin!

**Comment by eventhough** [comment]
Adding on to what @nelsonic  just said....you might want to separate your token refreshing code from your hapi-auth-jwt2 strategy. You can write a standalone plugin that hooks into the `onPostAuth` extension which can issue a new token. That would help separate the concerns?

http://hapijs.com/api#request-lifecycle

**Comment by nelsonic** [comment]
@eventhough great point! :+1:

**Comment by Dindaleon** [comment]
I am trying to make a new plugin that hooks into the `onPostAuth` extension as @eventhough mentioned, which is a great and clean way of doing it. However, I am having some difficulties.

First, I tried the `onPostAuth` extension and nothing was being returned when making requests to my server, so I am using the `onPreAuth` extension. I do not know if this is ok though.

Second, the only way I am able to get the expired token is within the `headers` property `request.headers.authorization`

Afterwards, I would verify the token with jsonwebtoken package. If expired, issue a new one, else continue with the current one.

I think that all of this would defeat the purpose of using the `hapi-auth-jwt2` plugin. So, I need some advising on how to proceed with this.

**Comment by eventhough** [comment]
I guess this makes sense...if the token is expired, hapi-auth-jwt2 probably short circuits the response and automatically sends out a Boom.unauthorized() response. @nelsonic correct me if I'm wrong.

I think you have three options here. Basically what you want to do is constantly refresh expired tokens. If that's the case then here are your three options:

1. Set `ignoreExpiration` to true and use `onPostAuth` to check expiration manually and respond with a new token.

2. Set `ignoreExpiration` to false and use `onPreAuth` to check expiration and short circuit the response process with a new token (before it hits hapi-auth-jwt2)...if token is NOT expired, `reply.continue()` and let hapi-auth-jwt2 handle token validation.

3. Forget all this stuff and create a new endpoint designed purely for refreshing tokens. I mean...this is probably what you want right? Basically your front-end checks the expiration every so often and if the user is still active (meaning user has taken some action) and the token only has like 10 minutes left, send out a request behind the scenes and update the user's token.

Because technically the user **was** asking for some resource right? Let's say your user was getting a list of /dogs and then you respond with a new token...isn't that weird? It kinda makes your REST api strange right?

Think about when you log into your bank's website...you have to stay active otherwise your session expires in like five minutes. This is good because you probably do not want your users leaving their laptops unattended while their bank account session is active...so you make the session VERY short and you keep refreshing the token as long as the user is active.

**Comment by Dindaleon** [comment]
Well, I would've liked to go with the first option. However, I don't know how to use `onPostAuth` because as I said, I am not getting any response when using it. The second option sounds interesting and I might go that way.

With respect to your last point, I would like to let you know my reasoning behind the usage of resfresh and access tokens, please correct me if I am wrong:

1. User logs in with some credentials (username and password).

2. Auth server issues refresh and access tokens.

  * Both tokens contain a unique identifier for that session. 
  * Refresh token may contain a expiration date and a check to see if it has been revoked.
  * Access token contains a short expiration date (15 min) and some data about the user (id, scope...)

3. Refresh token is saved in the database and the access token is saved in the user's side in a local storage or in a cookie. (What would you say is a safer place to store the access token?)

4. For every user request to the resource server, the server validates the access token.

  * Checks to see if the user is who he says he is.
  * Checks if the token has not expired. 

4a. If the access token is valid, the requested resource is returned to the user. No calls to the database are made at this point.

4b. If the access token has expired:

   * Checks back to the database for a valid non revoked refresh token
   * If it's valid and non-revoked, checks if the unique identifier matches the one in the refresh token.
      * If it matches, issues a new access token.
      * If it doesn't, the user has to re-authenticate.

I know, it is kind of off topic, but I am new to this Oauth flow, so any advice and help would be greatly appreciated.

**Comment by eventhough** [comment]
@Dindaleon Unfortunately I think this discussion has now moved beyond the scope of hapi-auth-jwt2. I'm not an expert on authentication so I am hesitant to give you any more advice.

If `onPostAuth` does not run when you set `ignoreExpiration=true`, that *might* be a problem with hapi-auth-jwt2. If you want, you can submit a PR with a test case that sets `ignoreExpiration=true` while also having an `onPostAuth` plugin.

**Comment by Dindaleon** [comment]
@eventhough I understand, thank you for the help.

`onPostAuth` works only when I return true on `validFunc` function. I don't know if it is suppose to work that way.

**Comment by schettino** [comment]
Reissueing a token after the current one has expired only makes sense if you have a blacklist flow. Otherwise, it can be dangerous because all the expired tokens will always be valid.
To work around with that, you can use a blacklist scheme, so if the token has expired, you chack if the token id is already on the blacklist, if so, throw a invalid request error, but if it's not, then you issue a new token and put on the blacklist the older one, It is more secure.

But I prefer having a refresh flow standalone, so I can keep concerns separated. And you can improve the flexibility on the refresh flow also. Let's say that on your validateFunc, you check how much time is left for that token. If has less then 5 minutes you issue a brand new token (just access tokens here) and send attached with the response.

**Comment by Dindaleon** [comment]
@schettino thank you for your feedback. I don't understand how an expired access token can still be valid. Whenever an expired access token is sent to the server, an error is thrown saying that the token is no longer valid, then a refresh token is sent from the client to the server and if it is valid, a new access token is issued. So, could you please explain me how this expired access token can be used to request resources from teh server?

**Comment by schettino** [comment]
@Dindaleon Sure!

Let's say we have an endpoint "/refresh" which receives the recently expired jwt and changes for a new one. In order to make it possible,  we have to bypass the hapi-auth-jwt2 validation and work around with a securely method . So, basically here is what we need to do:

Step 1)
let jwt = require('jsonwebtoken');
let Boom = require('boom');
function refresh(access_token) {
	jwt.verify(access_token, process.env.API_KEY, function(err, decoded) {
		if (!err) throw Boom.badRequest('Token is still valid');
		if (err.name !== 'TokenExpiredError') throw Boom.badRequest('Invalid Access Token');
	});
	let payload = jwt.decode(access_token);
	return payload;
}

Note that doing this we not compromise the integrity of our authentication flow, since jwt.verify method is called to verify the signature, just like hapi-auth-jwt2 does. The difference here is that we are expecting an error (TokenExpiredError) to be thrown. If it's not, it would break our logic model and stop the refresh flow. The second thing to note here is that after verifying the signature and working around with the error we need, properly, we call jwt.decode (which not verify the signature) just to get access to the payload. This lead us to the next step.

Step 2)
To make it short, now that we have the payload from the expired token, we look up for the "jti" claim (JWT ID) in our cache database. If there's no results, it means that this token have never been refreshed and we are good to go to the final step. On the other hand, if the jti is found on our database, we throw a error and stop the refresh flow.

Step 3)
Now we're great to make the refresh happen. We issue a new access token and put the older one on the blacklist (cache database). And this is it.

There are some things we could improve here, of course. It's a different path to work with a refresh flow and it's not a definitely way for doing it, so feel free to point out some improvements or mistakes.

**Comment by nelsonic** [comment]
@Dindaleon you now have ***Complete Control*** over the `verify` flow using a `verifyFunc` therefore you can re-issue the token if you want to. let us know if you need an example for how to do this.
(*please re-open the issue if you feel the latest release does not give you enough control...*)
