### ISSUE TITLE
Change module name

### ISSUE THREAD

**Issue by vdeturckheim** [dwyl/hapi-auth-jwt2#138]
Hey, 

Following [this article](http://hueniverse.com/2015/09/10/the-myth-of-descriptive-module-names/) maybe the use of another name would be funnier/better ?

**Comment by nelsonic** [comment]
Yeah, Eran Hammer has a *talent* for naming his modules and that blog post is *genius*,
however I think this module *benefits* from the *descriptive* name because it does *exactly* what the name suggests. If it were called "*ferret*", "*bouncer*", "*trumpet*" or whatever "*creative*" sounding name we can think up, people would *never* be able to find it ... 

At present [**hapi-auth-jwt2**](https://www.npmjs.com/package/hapi-auth-jwt2) is *the* ***most popular Hapi Auth module*** (*by number of downloads*) on NPM *ahead of* "[**Bell**](https://www.npmjs.com/package/bell)" which is the "*Official*" way of doing 3rd Party Auth in Hapi... 

So while I would actually *like* to use creative names, I think the *descriptive* names are actually *better* for not confusing beginners/non-native-english-speakers and for helping people to discover/use the package...
