### ISSUE TITLE
No access to JWT header?

### ISSUE THREAD

**Issue by cvillerm** [dwyl/hapi-auth-jwt2#152]
First of all, this is a great plugin with active contributions!
I saw recent enhancements about dynamic key lookup and custom verification functions.
However, I am missing simple ways to access the full JWT in these functions. Only the decoded *payload* seems to be transferred.

We are working with JWT created with the [x5t header claim](http://self-issued.info/docs/draft-jones-json-web-token-01.html#ReservedHeaderParameterName). This contains the thumbprint of the certificate (public key) using for signing the JWT. I find this to be a more elegant way to define what key was used to sign, as opposed to storing a key identifier in the payload.

When decoding the JWT and passing it to lookup or verification functions, could it be possible to be able to pass the full JWT (e.g. by passing option `{complete: true}` to `JWT.decode` so that all part will be available for use)?

**Comment by nelsonic** [comment]
@cvillerm Great Question! 
Firstly, if you are receiving the `JWT` in the request headers, you still have access to the JWT via `request.headers.authorization`
Using the [x5t header claim](http://self-issued.info/docs/draft-jones-json-web-token-01.html#ReservedHeaderParameterName) is a good idea. Given that we have the *ability* to use a *custom* key derivation function you can simply extract the `x5t` from the `request.headers`.

Apologies if the documentation does not make this clear...

**Comment by cvillerm** [comment]
3 comments:
1. in case the token is passed as cookie or on the URL, I think that we would have to figure out where to read the raw token from. This wouldn't be in `request.headers.authorization`
2. the verifyFunction has the `request` available directly as a parameter, but not the key lookup function
3. `x5t` is a claim in the JWT header (could be found in `decoded.header` if `decode` could contain the whole JWT and not only its payload), not a request header, i.e. this isn't found in `request.headers`

What about adding another verifyOption (e.g. can be set as `{complete: true}`) that would be passed to the JWT.decode calls? If this option is set, callbacks would receive the whole decoded JWT.

**Comment by nelsonic** [comment]
All good points. I mentioned that the JWT is available in the `request.header` because that's what you said you were using... but it *could* be accessed just as easily from the URL or cookie. 
At present we are not making this *easy* but we haven't had a *request* for the RAW JWT Token before else we would simply make the [`extract.js`](https://github.com/dwyl/hapi-auth-jwt2/blob/f557f81d9811d797a82c64798a4add7229bb4528/lib/extract.js) *accessible*.

*Technically* the `key` lookup function gets executed in the scope of the [`authenticate`](https://github.com/dwyl/hapi-auth-jwt2/blob/f557f81d9811d797a82c64798a4add7229bb4528/lib/index.js#L27) execution, 
so it has access to *all* the variables its "*parents*" have ... 
so: `request`, `reply`, `server` and `options`.
Try this: 
```sh
git clone https://github.com/dwyl/hapi-auth-jwt2.git
cd hapi-auth-jwt2
npm install
```
Now *copy-paste* the following line *anywhere* from lines [53-80](https://github.com/dwyl/hapi-auth-jwt2/blob/f557f81d9811d797a82c64798a4add7229bb4528/lib/index.js#L52-L81):
```js
console.log(' - - - - - - - >', request.method);
```
then run:
```sh
npm test
```
Check your terminal. expect to see: `- - - - - - - - > post`

Now, as for getting the `headers` when decoding the token, yes, absolutely, that makes *perfect sense*.
Do you have time to send us a Pull Request adding the feature?
see: https://github.com/auth0/node-jsonwebtoken/blob/c548032fb698049743c74e6355bb3e425eeec823/test/set_headers.tests.js#L7-L9

**Comment by cvillerm** [comment]
Thanks again for your answers.
I don't think that I ever wrote that I wanted to use a JWT available in `request.headers`, but I could have written explicitly that I wanted to support several use cases with the JWT sent as authorization header or cookie, hence the need to access this token, whatever way it was sent.

I figured out that the token retrieved is stored in `request.auth.token` just after it is extracted from the request, and this may be the good way to access it in a custom function. By the way, I saw that the token will eventually be saved both as `request.auth.token` and `request.auth.artifact`. Is this expected to have this stored twice?

I tested accessing `request.auth.token` in a dummy key lookup function:

```
internals.keyLookupFunc = function(decoded, callback) {
	console.log("keyLookupFunc: Token: "+JSON.stringify(decoded));
	console.log("keyLookupFunc: request.auth.token: "+JSON.stringify(request.auth.token));
	var header=JWT.decode(request.auth.token, { complete: true } ).header;
	console.log("keyLookupFunc: header: "+header);
	callback(false, 'whateverkey'); // (err, key, extraInfo)
}
```
But this fails when trying to access object `request` (ReferenceError: Uncaught error: request is not defined).

In a verify function, `request` is indeed available, so this may be a way for me to have access to both the JWT headers and payload in a custom verification function (in which I will lookup for what key to use to verify the token).

When I will find time, I will anyway try to work on a way to ask that `decoded` returns the complete token (header+payload) as I think that making the header available in custom function would be useful.

**Comment by cvillerm** [comment]
I just created a pull request for this. A new option `completeToken` will make the full token available to key lookup and verify functions.

**Comment by cvillerm** [comment]
As a side note, another example of key lookup function needing to access the token header is in the context of an [OpenID Connect](http://openid.net/connect/) ID token (formatted as a JWT), with a `kid` claim in the header. `kid` is used as a key identifier, that can then be used to retrieve the corresponding public key from a trusted provider of JSON Web Keys.

**Comment by nelsonic** [comment]
@cvillerm the latest version on NPM has this feature. :+1: 
Please close the issue when you have it up and running in your app. thanks again. :tada:

**Comment by cvillerm** [comment]
Tested successfully with npm package 5.7.0.
Thanks!
