### ISSUE TITLE
verifyFunc override 

### ISSUE THREAD

**Issue by gbd77rc** [dwyl/hapi-auth-jwt2#175]
Hi 

Should it not be the token passed to the custom verify function instead of the decoded object?  This would allow the custom verify function to lookup signing key based on the information within payload, and then verify the JWT is signed with that key.  Or am I missing the point of this function?

I can understand that validate function would have just the decoded object as this is post signing check.

Regards

Richard...

**Comment by nelsonic** [comment]
Hi @gbd77rc, great question, when using a _custom_ `verifyFunc` you get the `decoded` token as the first argument, because the JWT should decode _regardless_ of what key was used to encode it.
If we _failed_ to _decode_ the JWT (_it means the JWT is not valid_), do you still _want_ to _continue_ with the request lifecycle...?
How you chose to ***verify*** the token and which `key` the JWT was signed with is still 100% up to you in your `verifyFunc` and you have access to the `un-decoded` JWT in `request.auth.token` ...

**Comment by gbd77rc** [comment]
Hi, thanks for the reply I tested that out yesterday, and it worked. I did not see that request.auth.token had a value. That makes sense now.

Richard...
