### ISSUE TITLE
Is it safe to use JWT to sign some data to be used in a user activate url

### ISSUE THREAD

**Issue by JMurphyWeb** [dwyl/hapi-auth-jwt2#196]
It is very important that the URL is not guessable and is unique.
When sending out our activation emails, is it safe to encode the user that can register into the url that we send out?

```
'people/activate/?token=' + jwt.sign({userId: 123}, secret)
```

The user will receive a link in which they can activate their account.

I am currently using iron to do the job of encrypting but would like to replace with JWT if it is considered safe.

**Comment by nelsonic** [comment]
@JMurphyWeb _great_ question!
You are emailing a `link` to a person which when _clicked_ will _verify_ their account (_and presumably log them into your app_). The link contains a JWT which `hapi-auth-jwt2` will decode/verify for you and make available as `request.auth.credentials` 

Putting a JWT in the URL is "safe" given the following if the following two conditions are met:
+ The person's email address is on a _secure_ server.
+ You are using HTTP_S_ on your Web Application
+ You invalidate the token after it is used (_to prevent it being reused if it falls into the wrong hands_)

Let me know if you need more _detail_. 👍

**Comment by JMurphyWeb** [comment]
@nelsonic thanks for info.

I am trying to understand the differences between something like iron and jw, which leads me to 2 questions:

1. Can you point me to a resource which you value which can bring me up to speed with basic security concepts and rules? More an introduction than anything.

 2. Of your three conditions, would any of them **not** stand if we were using iron encryption?

**Comment by bitcloud** [comment]
One of the biggest differences a lot of people don't see afaik is that JWT is per default *not encrypted*. Basically it is *base64 encoded and signed data*. So everything you store in that token can be *decoded by the client*. The server additionally checks the signature that the data was not tampered with. And there is more structure to JWT like headers and required fields in the payload.

With iron you have encrypted tokens without predefined structure of the payload.

But as @nelsonic already mentioned. Security on both is based on that this token stays in the right hands. Concerning verification in email links. This should be a one time pad in most cases. Otherwise it would be something like a password reset link you can use over and over.

In you usecase you can use token but I would use it even more then. If it is in the process of an user signup and you have a lot of dropout at that stage you don't want to have in your DB, you can store the full profile in the token of the user that should be created when he clicks the link.

That would be the usecase to keep you db clean.

If you have them in the DB anyway then I wouldn't use JWT because the hashed (userid (+ expiry date if needed) + secret) should be sufficiant.

Imagine this URL http://yourservice/activate?userid=123&expiry=2017-04-30&token=hash
This should provide enough security for your usecase.

**Comment by nelsonic** [comment]
Closing as long since resolved. ✅
