### ISSUE TITLE
Multiple JWT Auth Strategies not Working

### ISSUE THREAD

**Issue by taywrobel** [dwyl/hapi-auth-jwt2#217]
In our application, we have multiple types of JWTs that we authenticate with; from users, and from applications for instance, and each type is valid for a (potentially overlapping) subset of routes.  Looking through the documentation, it seemed as tho the best approach for handling this would be to have two separate strategies for each type, and apply those strategies to the routes as appropriate, however, it appears that only the first strategy listed is ever run.

My strategies are configured as follows:
```js
server.auth.strategy('userJwt', 'jwt', {
  key: require('./utils/keyLookup'),
  //validateFunc: require('./utils/authJwtValidate'),
  verifyFunc: require('./utils/authJwtValidate')
});

server.auth.strategy('applicationJwt', 'jwt', {
  key: conf.get('jwtSigningToken'),
  validateFunc: require('./utils/applicationJwtValidate'),
  verifyOptions: {
    issuer: false
  }
});
```

Each strategy works fine by itself.

An example route that should be able to authenticate with either type of JWT follows:
```js
server.route([
  {
    method: 'GET',
    path: '/v2/projects',
    config: {
      auth: {
        strategies: ['userJwt', 'applicationJwt']
      },
      handler: projectsController.index,
      ...
    }
  },
  ...
]);
```

However, when the route is hit, only the first listed authentication strategy is run, and if it fails, the server immediately responds with a 401, rather than moving on to trying the next one.  Am I missing something about how multiple configured authentication strategies is meant to work?

Thanks in advance,
-Taylor

**Comment by twrobel3** [comment]
Some more digging done on this - it looks like the Hapi auth handler looks for the `isMissing` [attribute on the error](https://github.com/hapijs/hapi/blob/master/lib/auth.js#L383) to decide if to run the next auth strategy.

And Boom only sets this flag if an `unauthorized` error is [created without a message](https://github.com/hapijs/hapi/blob/master/lib/auth.js#L383) for some reason.  I'm relatively new to Hapi, so I don't know what the actual meaning of these flags are, or the repercussions for changing them, but I can get the multiple auth strategy chain working as expected by setting the `isMissing` flag manually on the error returned by `raiseError`.

If someone more familiar with the frameworks at play here has a better idea on how to do this, or what the repercussions of this approach would be, I'd love some feedback :)

**Comment by twrobel3** [comment]
Found an application-level workaround:  If the `validateFunc` of `verifyFunc` throws their own `Boom.unauthorized` with a `null` message, the chaining happens as expected.

For anyone else looking to do this, here's the approach I'm going with: At the top of each `validateFunc`, first check the JWT type, however you're storing it.  If it doesn't match that validator, return a `callback(Boom.unauthorized(null, 'jwt');`, which will chain on to the next strategy, if there is one.  Once there are no more, Hapi will return a 401 with the message "Missing credentials" (not super helpful, but workable).

Then proceed on with the rest of your validations, and if there are actual validation errors, return an unauthorized Boom with a non-null message, which will abort the strategy checking and return your message all the way up the reply chain.

**Comment by nelsonic** [comment]
@twrobel3 _thankyou_ for posting this issue! sounds like you _may_ have figured out how to do what you need. if not, can you please formulate a `user story` out of your use-case so we can _understand_ ***exactly*** what is required. thanks! 👍

**Comment by twrobel3** [comment]
Hey there @nelsonic 

I have figured out a solution that works for me, but it's definitely confusing when you first encounter it (likely more to do with how Hapi expects auth strategies to behave, more than any implementation problems in this library).  I'm not entirely sure what goes into a `user story` or where you expect them to be posted, but I'd be happy to better organize the problem I encountered and the underlying causes into one, if you let me know where you'd like it to be posted

**Comment by nelsonic** [comment]
@twrobel3 ultimately, this is a _use-case_ that _other_ people might need ...
So it would be _great_ to capture it in the https://github.com/dwyl/hapi-auth-jwt2#frequently-asked-questions-faq- section so that others don't have to _suffer_ the way you did to get it working...

**Comment by twrobel3** [comment]
Alright, sounds good.  I'm going to spend time tomorrow trying to make sure I have it working, then I'll add a more succinct write-up here, as to what can be added to the FAQ.

However, one part of the code that I think should change has to do with the error handling for the initial checks for validity of the token.  I'm looking at [`index.js:117`](https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L117) and [`index.js:126`](https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L126).  I would suggest changing them to set the message to null, rather than to `'Invalid token format'`, similar to [`index.js:113`](https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L113).

The reason for this is that by setting a message, you prevent any subsequent auth strategies from being run, which may be incorrect behavior.  For a concrete example, suppose you have a route that can be authenticated via either basic auth or JWT auth.

Under the route config you have:
```js
auth: {
  strategies: ['jwt', 'basic']
}
```

And a user comes in with valid basic auth credentials:
```
Authorization: Basic 12345678
```

The authenticate function is called, and the token exists, so the condition on [line 113](https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L113) is not met.  Instead, the token validity check fails, and the return statement on [line 117](https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L113) is called.  Since this sets the message of the unauthorized error, Hapi will immediately reply to the request with a 401 error, even tho the user had valid credentials for basic auth.

If instead those two return statements did not set a message on the 401 response, the next strategy (the basic auth, in this example) would be executed.

**Comment by nelsonic** [comment]
@twrobel3 sweet! 🍭 
I've invited you to be a `member` of @dwyl on GitHub https://github.com/dwyl
so you can create your _addition_ to the FAQ on a _branch_ on the repo and assign to me for review.
(_thanks_!) ❤️  ✅

**Comment by steefanfuchs** [comment]
Just ran into the same problem.
I could not follow your Application Level Workaround because the errors were thrown before entering the validateFunc. Im trying to chain a jwt with an hmac-signature strategy and the error is thrown at the token validation. 
Is there already a solution for this?

**Comment by LabiKyo** [comment]
same here.  the errors were thrown before entering the `validateFunc`. so only `verifyFunc` will work?

**Comment by bujardeari** [comment]
@twrobel3  Did you find a better solution? Or could you post more code from you solution?

**Comment by jakebarnett** [comment]
@twrobel3  Thanks for the info, very helpful.

To those of you who are seeing issues where errors were thrown before entering the validateFunc, try reimplementing the validation logic in verifyFunc.  If JWT.verify fails, catch the error it throws and instead throw your own with a null message.  Heres what I did:

`server.auth.strategy('myStrategy', 'jwt', {
  key: 'MySecret',
  verifyFunc: (_d, request, callback) => {
    try {
      const decoded = JWT.verify(request.headers.authorization, 'MySecret');
      if (decoded) {
        return callback(null, true);
      }
    } catch (e) {
      return callback(Boom.unauthorized(null, 'jwt'));
    }
    return false;
  },
});`

**Comment by ablackbu** [comment]
Hi, 

I've been having the same issue on hapi v17.5.1  and hapi-auth-jwt2 v8.1.0. I have two different authentication plugins both using hapi-auth-jwt2. 

I don't know if this is the correct area but I am a bit new to contributing fixes back. I haven't fixed the broken test yet (since its getting late) but this does fix the issue and allow multiple authentications.  I would be curious if this was the correct fix or how we should go about it? Also would I be able to get the test Redis Cloud url since I don't think I can fix them without it. 

Hope someone can take a look and that this helps. 

https://github.com/dwyl/hapi-auth-jwt2/pull/277

**Comment by ablackbu** [comment]
As an update. I've found that in my use case putting a custom errorFunc will workaround it if anyone can't wait for the PR to get approved, etc. 


`            errorFunc: (errorContext) => {
              errorContext.message = null;
              //return Boom.unauthorized(null, 'bullshit');
              return errorContext;
            }`

**Comment by nelsonic** [comment]
Appears that everyone in this thread has found a solution. 👍 
If still an issue, please open a fresh issue so we can resolve as fast as possible. 
Thanks.
