### ISSUE TITLE
Question: What do I do in validateFunc?

### ISSUE THREAD

**Issue by mattc41190** [dwyl/hapi-auth-jwt2#226]
I am implementing JWT in a small web app and I am certain this is a newbie question, but what are you supposed to do in the validate function? I was under the impression that all state and validation data was held on the client side and that as long as the token was 1. valid and 2. not expired that the request was already "validated". 

However in the examples shown on your code page you do a user lookup on every request. **Is the implication here, that I ought to be validating the user in the DB for every request using this auth strategy?** As you can see I am new to this stuff, so if this is old news please forgive me, but if possible I want to avoid going to the DB for every request.

**Comment by nelsonic** [comment]
@mattc41190 if you don't want to _invalidate_ a given token, then you don't need to check it's JTI in a database/datastore in which case your auth is indeed "stateless". 
Please help us understand your **use case** by providing a bit more insight into what your "_small web app_" _does_... 👍

**Comment by mattc41190** [comment]
Certainly, @nelsonic I will include some snippets as well. It is a blog site. About as simple as they come. Any unlogged in user may get a single blog post or a list of recent blog posts. In order to create a post the user must be logged in. 

The login process looks a bit like:

``` javascript
// login handler
exports.login = function(request, reply) {
	let self = this;
	let email = request.payload.email;
	let password = request.payload.password; //currently stored in clear text working on it...
	this.db.getDocumentByEmail(users, email, function login(result) {
		let userData = result[0];
		if (userData.password === password) {
			let tokenConfig = {
				"expiresIn": "1 day"
			};
			let token = self.jwt.sign(userData, request.server.app.secret, tokenConfig);
			reply({
				token
			});
		} else {
			reply("bad auth....");
		}
	});
};
```

The token is then attached to subsequent requests in the form of an authorization header, for instance a full create request may look like:

```  javascript
// client create blog post

login = {"stuff": "for", "making": "a", "dope": "login"};
createPost = {"stuff": "for", "making": "a", "dope": "post"};

rp(login)
	.then(function(loginResp) {
		let token = loginResp.token;
		createPost.headers = {
			'authorization': `Bearer ${token}`
		};
		return rp(createPost);
	})
	.then(function(createPostResp) {
		console.info(createPostResp.statusCode);
	})
	.catch(function(err) {
		console.error(err);
	});
```
 
In this example I don't know what the validateFunc should be used for. If the authorization header is not a valid object once it is decoded the request fails. __My question I suppose may be more generic in nature and it is, should the user be looked up in the DB using the data from the authorization header upon each request for a secure resource?__ And if this is the case is there any way to bundle those network requests into one item so that I don't create 2 DB connections on every secured resource request?

It means so much to me that you are helping me out. I have never done security before and feel out of my depth.

**Comment by mattc41190** [comment]
@nelsonic *bump noise* :)

**Comment by mattc41190** [comment]
@nelsonic _bump bump_

**Comment by gbruins** [comment]
@mattc41190  I also am not a JWT expert but I'll give you a dump of what I know in hopes it will help answer your question.  Perhaps an overview of the JWT process would be helpful:

1) Client requests a token (providing credentials)

2) Server checks credentials and creates a token (if credentials are valid)

3) Server sends JWT to the client

4)  (optional) Client verifies the token to make sure the data it contains has not been tampered with since being sent from the server.  

5) (optional) Client extracts the 'claims' from the JWT payload for use in the application (those claims may relate to user privileges perhaps)

6) Client persists the token client side (localStorage, cookie, etc)

7) Client uses the same (persisted) token for subsequent requests to the server


HERE'S WHERE YOUR QUESTION IS, I THINK:
--------------------------------
8) Server verifies the token for all subsequent requests (the most important part of this process)

- Server receives the JWT from the request (perhaps from the request header 'Authorization: Bearer [JWT]', or 'Authorization: [JWT]'...both styles are equally valid:  https://github.com/dwyl/hapi-auth-jwt2/issues/6)

- hapi-auth-jwt2 will verify that the JWT is valid, using jsonwebtoken.verify():   https://www.npmjs.com/package/jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

- If the JWT is valid, then your custom 'validateFunc' will be called, for any extra validation you may want to do (verifying the user in your DB, per your example above).  This is not required though, since the JWT has already been verified as being valid.   I suppose the function you define as the 'validateFunc' can simply return true if you don't wish to do any additional validation.

**Comment by mattc41190** [comment]
@gbruins thanks for reaching out. that is my understanding as well. Basically I just return true from the function since the JWT package has already confirmed that the token is in fact valid. For some reason I felt and still feel that I should be DOING something else in there lol, but doing a DB lookup every time seems like overkill.

**Comment by bitcloud** [comment]
just to wrap up here: you don't need to implement a validate function. What you get with jwt is is a cryptographically secured "ticket" to access your app. If it is not valid, every auth_jwt secured route will be blocked by the plugin. nothing else to do.

To use that you need to encode all the required information for a user session (e.g. username, userid, permissions, ...) in that token otherwise you would need to fill it up with an database query anyway.

the problems with that approach begins when you have volatile information in that token. As an example we store the current theme at the user as well. 
This is now stored in the JWT token on your computer and in the user database.

If you now use you friends computer and change the theme there it is again stored in the database and on your friends computer jwt token.

If you now go back to your computer, the user session is restored from your computer jwt token without consulting the user database. So you get the old theme setting.

you get the idea?

You'll have the same problem with changing permissions or early invalidation of the token.
Once you signed the token and handed it to the user, you can't control and change it anymore.

So depending on your requirements you need to implement a validate function to check valid jwt tokens if they are still valid in your context. If you consider this and you are still ok, no validate function is still a valid option.

If this answers your question please close the issue :-)

**Comment by bitcloud** [comment]
ok, as had a quick look in the code. You need to provide a validateFunction for this plugin to work.

I think this shouldn't be enforced per se. What do you think @nelsonic ?
It should be perfectly valid to not supply one and just depend on the expiry check that is done by jwtwebtoken itself.

For now, if just the check for a valid and not expired token is sufficient it is ok to just do

```
var validate = function (decoded, request, callback) {
  return callback(null, true);
};
```

**Comment by acmoune** [comment]
@mattc41190 If your main concern is I/O latency, I suggest that when a user log in, you store all his needed details in the server cache (redis or whatever), so your jwt can have only one claim: the cache entry key, and in your validateFunc, you just retrieve the full account details from the cache using that key. Those details can be username, permissions, theme, whatever, and the cache is super fast. When the user log out, you just destroy his cache entry.

I hope this helps.

**Comment by nelsonic** [comment]
Question answered in 2017. Hopefully this is clarified. Closing. 👍
