### ISSUE TITLE
clarification Needed

### ISSUE THREAD

**Issue by prudvihemanth** [dwyl/hapi-auth-jwt2#247]
HI,

Is there any need to use 'secret Key' in the  auth.strategy method. Is it not sufficient to provide it at the time of jwt creation. 

I doubt if this is needed, it is for pre validation  before going to validate function. Am I right?

Please explain

Thanks
pruthvi

**Comment by nelsonic** [comment]
@prudvihemanth apologies if this is unclear from the code. You need to supply the Secrete Key when registering the plugin because the plugin with `verify` the JWT on each request.
see: https://github.com/dwyl/hapi-auth-jwt2/blob/f2560e65548a7763433fbe599dca39b5eb175ce6/lib/index.js#L150
Without the Key verification is not _possible_.

**Comment by nelsonic** [comment]
Clarification given. No further response. Closing. ✅
