### ISSUE TITLE
how can I use hapi-auth-jwt2 with a refresh token 

### ISSUE THREAD

**Issue by aro1976** [dwyl/hapi-auth-jwt2#252]
Is it possible or anyone implemented hapi-auth-jwt2 with an refresh token?

The scenario I'm planning is to have the following :
1. Access token with 30min expiration
2. Refresh token with 7 day expiration
3. Every time Access token is about to expire, there would be a /refresh call in background using the refresh token that would replace both refresh and access token.
4. If the Refresh token is revoked, the /refresh fails with unauthorised error and directs user to authenticate again.
5. Access token should never be validated against database

Thanks for any advice,
Alessandro.

**Comment by george-iuriet** [comment]
Hi @aro1976,

One easy solution is to combine these two tokens (refresh and access) into only one. 

1. Token's `exp` property set to 7 days
2. An additional `useExp` property set with 30 mins
3. When you make /refresh call, you update the `useExp` property, so that it will get additional 30 mins
4. If the session for a user is ended in the DB, refreshing the token will be denied.
5. In the `validateFunc` only validate the `useExp` property, something like this:

```
export default function validate (decoded, request, callback) {
  // at this point, token's exp property (refresh token) is valid
  // it is not validated against the DB session
  if (decoded.useExp > Math.floor(new Date().getTime() / 1000)) {
    // useExp (access token) is valid
    return callback(null, true)
  } else {
    // useExp (access token) is not valid
    return callback(null, false)
  }
}
```
What do you think?

**Comment by nelsonic** [comment]
Refresh tokens are beyond the scope of this plugin as they are handled by `jsonwebtoken`. 
No response from OP in 3 years. 
Closing.
