### ISSUE TITLE
Accept token as route parameter

### ISSUE THREAD

**Issue by felipegcampos** [dwyl/hapi-auth-jwt2#263]
Would there be any problem adding the token to the route parameter?

`${route.path}/{token}/{param*}`

This would be great for embedded static content authentication using inert without the need to use cookies.

Please, share your thoughts.

**Comment by nelsonic** [comment]
Given that `?token=jwt` is available you can still do `/{path}/{param}?token=jwt`
the reason we haven't added tokens as a route param is because JWTs tend to be very long so we usually just put them at the _end_ of a URL query string.  e.g: `/notes/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c/edit` is not a very friendly URL ...

By contrast, putting the JWT at the end makes it a bit clearer:
`notes/1/edit?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c` 

If you would still prefer the ability to have the Token in the path, please re-open and create a PR.
Thanks.
