### ISSUE TITLE
How can we add data to request.auth.artifacts?

### ISSUE THREAD

**Issue by ozum** [dwyl/hapi-auth-jwt2#284]
It is asked in #224 a year ago, but I could not find an answer.

How can we add data to `request.auth.artifacts`?

**Comment by cilindrox** [comment]
@nelsonic would you accept a PR addressing both this and #224 ?

Running into the same scenario where artifacts would be more convenient as an object. I realize this is a breaking change, so wanted to ask before putting in any work.

**Comment by nelsonic** [comment]
@ozum thanks for opening this issue to remind us access to `request.auth.artifacts` can be useful for certain use cases. 👍 (_even if we @dwyl aren't using them it makes sense for us to support this!_)

@cilindrox we will definitely accept a PR provided it has minimal code changes just to add this feature.
Please create a branch in this repo (_not a fork_) so that we can help with docs/tests if you want to focus on functionality. You have been invited to be a colaborator/contributor to the project so you don't need to fork just: 
```
git clone git@github.com:dwyl/hapi-auth-jwt2.git && cd hapi-auth-jwt2
git checkout -b 'request-auth-artifacts-issue#284'
```
Then write code, git commit it referencing this issue and push to GitHub. :shipit: 

The simplest implementation for accessing `request.auth.artifacts` that I can find is:
https://github.com/johnbrett/hapi-auth-bearer-token/blob/dbdd0540bb4a249844f95a98fb01c096f51a364a/lib/index.js#L79

With the corresponding test: https://github.com/johnbrett/hapi-auth-bearer-token/blob/1d306551feb5417fc85ac28de6b68d314739b5a5/test/index.js#L70

For anyone else watching the repo following along, the best explanation for "what are authentication artifacts used for in hapi.js" is by @mtharrison https://stackoverflow.com/questions/29177093/what-are-authentication-artifacts-used-for-in-hapi-js-authentication-schemes 👀

**Comment by cilindrox** [comment]
Thanks @nelsonic - Will send a PR your way!

**Comment by cilindrox** [comment]
@nelsonic I wasn't able to push directly to the upstream remote, so I ended up forking (perhaps I lack permissions on this particular repo?)
I've opened #341 with the changes - lmk if you'd rather have it on a branch on this project instead and I can close and reopen.

**Comment by nelsonic** [comment]
@cilindrox maybe you did not receive the invite ... 💭 
![image](https://user-images.githubusercontent.com/194400/76264057-8cf91680-6258-11ea-8716-2a5a88f98534.png)
Here's the link again: https://github.com/dwyl/hapi-auth-jwt2/invitations 🔗

**Comment by cilindrox** [comment]
All set - #342 is ready for review, thanks!

**Comment by nelsonic** [comment]
@cilindrox #342 merged. thanks again. 🥇 
@ozum the feature is live on `hapi-auth-jwt2@10.0.0` NPM :shipit:
