### ISSUE TITLE
8.7.0 alternative auth not working

### ISSUE THREAD

**Issue by dcharbonnier** [dwyl/hapi-auth-jwt2#325]
8.7.0 is preventing to have multiple auth possibilities, raising errors. the return of the authentication method have been changed and I doubt this is correct. At least it's a major incompatibility with all the previous versions, this should at least be a 9.x version, please unpublish this version

**Comment by nelsonic** [comment]
Hi @dcharbonnier _thank you_ for opening this issue. 
Could you please add more detail to help us _understand_ why you are experiencing auth failure?
Please add some sample code if possible so that if we can get to the bottom of the issue,
we can add regression tests to prevent failure in the future.

**Comment by dcharbonnier** [comment]
I have no time right now and the code on our side exploiting your lib is quite big so it require an investment to figure out the issue. Try to add multiple auth on an hapi route. Before this release if you had a basic auth and a jwt auth on the same route it was enough to have one auth valid, with this one the jwt raise somewhere an error with "token is null". That's not what's expected. if you check the changes in the index.js the way the missing auth is returned is different and _I guess_ this is the issue.

**Comment by dcharbonnier** [comment]
I think the error is only when you do POST requests

**Comment by stevenleadbeater** [comment]
I'm not sure where best to describe what caused this, it is down to the fact that Hapi auth itself is adding the isMissing flag to errors without messages which it subsequently uses to decide whether to try other schemes, this is not great for us as it means we have to throw errors without a message in order to cause multiple schemes to behave correctly. I've added a parameter to the raiseInternal method so we can flag an error as a missing token one, which adds the isMissing flag to the error.

**Comment by nelsonic** [comment]
@dcharbonnier please try `hapi-auth-jwt2@8.8.0` on NPM
which contains the improvements made by @stevenleadbeater for multi auth support. 
Thanks.
