### ISSUE TITLE
How to delete token on client to logout?

### ISSUE THREAD

**Issue by Baka9k** [dwyl/hapi-auth-jwt2#350]
Hello!

I want to use simple solution - use JWT without storing it in database, and perform user logout just by deleting JWT on client.
As I see in examples, JWTs are sent to client via setting response headers. So, my question:

Should I extract JWT from Authorization header and save it somewhere in my web app (e.g. cookies or localStorage), when app performs /login api call and gets JWT? And then set request header "Authorization" value to this JWT on every request on client? Or this header will be saved on client and used for every new request automatically, as it works with cookies? If it will be saved automatically, how do I remove it to logout user? I can't delete headers from request. Should I make /logout route on server just to use it to set response header "Authorization" to something invalid in this case?

Or if I'll use cookies instead of headers, cookies set by server should not to be "httpOnly" cookies, right? Otherwise, I will not be able to remove them with JS on client to perform logout. 
Where I can find example with cookies solution? As I see, both examples use headers.

**Comment by nelsonic** [comment]
@Baka9k thanks for opening this issue/question. 
`hapi-auth-jwt2` checks for a `JWT` in the cookies of all HTTP requests so provided you set a valid `JWT` in the cookie it will be validated (checked). Once you _unset_ the cookie e.g. as part of a "logout" event, it will no longer be available and requests to protected endpoints will be rejected.


The thing to note is that deleting/unsetting a cookie from the request or browser state does not _prevent_ a ["replay"](https://en.wikipedia.org/wiki/Replay_attack) because technically the `JWT` is still valid. The way to mitigate this is **either** use a `JWT` with a very short expiry ***or*** lookup the `JWT` in a "session" table in a datastore (e.g. Redis) and ensure that you invalidate the session when the person logs out. 

We do not have a _current_ example for this use case we can point you to. Sorry. 🤷 
Please see https://hapi.dev/tutorials/cookies for more detail.

**Comment by Baka9k** [comment]
@nelsonic Thank you very much for answer!
