### ISSUE TITLE
Difference from official https://github.com/hapijs/jwt ?

### ISSUE THREAD

**Issue by mariusa** [dwyl/hapi-auth-jwt2#351]
Hi, I'm just getting started with hapi. Trying to see what to use for JWT auth.

The official jwt module doesn't have any docs: https://github.com/hapijs/jwt

Would you please list the differences between this & official module? 
Would you consider asking the hapi team to make hapi-auth-jwt2 the official module, to reduce confusion for new users?

Thanks

**Comment by nelsonic** [comment]
Hi @mariusa thanks for opening this issue to seek clarity on this question. 🥇 

As you have noted, the **documentation** for  **`hapi-auth-jwt2`** is _comprehensive_ whereas the "official" module, as you have called it, has ***none***.  **`hapi-auth-jwt2`** is _never_ going to be the "official" module because the creators of **`Hapi`** cannot "own" it. The **`Hapi`** team could _easily_ have avoided the "_**confusion** for **new users**_" by not _creating_ the _undocumented_ copy module. 

https://www.npmjs.com/package/hapi-auth-jwt2 **`hapi-auth-jwt2`** has more useful/tested+documented features  [contributed](https://github.com/dwyl/hapi-auth-jwt2/graphs/contributors) by people in the community who _use_ the plugin in _thousands_ of Apps. 
![hapi-auth-jwt2-npm-downloads](https://user-images.githubusercontent.com/194400/91461507-03c6b200-e881-11ea-8a3e-d0c0572e3e18.png)

https://www.npmjs.com/package/@hapi/jwt is a copy without any documentation attempting to power-grab from the well-established community-maintained module because they have a _chronic_ case of ["Not invented here"](https://en.wikipedia.org/wiki/Not_invented_here) syndrome.
![npm-hapi-jwt-no-docs-low-usage](https://user-images.githubusercontent.com/194400/91435057-a2411c00-e85d-11ea-8757-7db0b090cdee.png)

## "_I can't stand anyone else's code, so I don't use anyone else's code_" <br /> ~ [Eran Hammer](https://youtu.be/qVMo54BUqEA?t=704) 

Instead of using a popular well-maintained, tested and documented **`JWT`** library like [`jws`](https://www.npmjs.com/package/jws) from [**Auth0**](https://github.com/auth0), 
they have re-implemented everything from scratch without clear reason _why_. 🤷‍♂️ 
If they at least had **performance benchmarks** to illustrate _why_ they needed to re-implement it, 
I would _understand_ the decision. But even then, why not just open an issue on _this_ repository so that the already popular module could be improved for all the _existing_ users? This _obviously_ creates confusion in the community, but they don't _care_.

If you are "just getting started" with **`Hapi`** I would advise you to _immediately_ consider an alternative. 
I would suggest you and anyone `else` reading this to **_stop_ using `Hapi`** and **switch** to something _faster_, more stable and a better Dev & User experience: https://www.phoenixframework.org

I don't say this lightly as I have invested *thousands* of hours in building Apps, [modules and _examples_](https://github.com/dwyl?q=hapi) for the **`Hapi`** ecosystem.
But I _regret_ using and promoting **`Hapi`**. There have been _so_ many **_breaking_ changes** over the years that it's been **_painful_ and _expensive_ to maintain** the  Apps we have built with it. I wish I could go back in time to 2014 and switch to [**`Elixir`**](https://github.com/dwyl/learn-elixir/issues/102) sooner. 😢 

I will continue to _patch_ this module so that the people who rely on it can **`continue`** using it.
But the writing is very much on the wall. By creating https://www.npmjs.com/package/@hapi/jwt, 
the maintainers of **`Hapi`** are saying: "_this is ours now_", they haven't made anything _better_ or more _performant_, just something they can _own_ and charge money for a [Commercial License](https://github.com/hapijs/hapi/issues/4114).

I won't be adding anything to the `README.md` of this repo as I don't want to say anything "_negative_".
But I _definitely_ would not use **`Hapi`** for any ***`new`*** Apps, there are _much_ better alternatives with less [_drama_](https://github.com/hapijs/hapi/issues/4111).

Sorry if this is not the answer you were looking for. 
I _really_ wish I didn't have to write this. 😞 
I just want to save you time. ⏳  == 💰

**Comment by mariusa** [comment]
Wow, I really appreciate your in-depth answer! Thanks so much @nelsonic , I'll stay away from hapi. Will stick to express and will look into phoenix too.

As a separate thanks, this project has one of the most impressive & useful set of docs I saw. For example, you point to JWT libs that can be used with node, but without hapi. Thanks Nelson!

**Comment by mariusa** [comment]
PS: Would be useful to have this 
https://github.com/dwyl/hapi-login-example-postgres
done with another framework that you recommend (express or phoenix), as a good example on how JWT auth should be handled in node.

**Comment by nelsonic** [comment]
@mariusa we already have a "[turnkey](https://en.wikipedia.org/wiki/Turnkey#:~:text=Turnkey%20refers%20to%20something%20that,supply%20of%20goods%20or%20services.)" authentication solution for Phoenix: https://github.com/dwyl/auth
We applied everything we learned from building auth systems at various companies and studying the implementation of Auth0, AWS Cognito, etc. Our code is always well-documented, tested and _beginner-friendly_. We know exactly how frustrating it is to be learning a new language/technology/framework/etc. That's why we write _comprehensive_ step-by-step tutorials for everything. e.g: https://github.com/dwyl/phoenix-todo-list-tutorial and https://github.com/dwyl/phoenix-chat-example

**`Express`** is good for lightweight Apps where you don't have too much application logic. 
The issue with **`Node.js`** in general is that being a [single-threaded event loop](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#:~:text=What%20is%20the%20Event%20Loop,the%20system%20kernel%20whenever%20possible.), **one error crashes the _single_ process**, i.e. a single (uncaught) error can bring down your site. So you end up having a lot of error-catching/handling boilerplate code ...
**`Elixir`** has _none_ of that. The VM assigns an ultra-lightweight process per _request/user_,
so if one request has an error nobody else is affected. It's a far more robust and scalable way of building things.

_Everything_ **`Hapi`** can do, **`Phoenix`** does **_much_ better**. 
Even if you don't end up _using_ **`Phoenix`**, you should add it to your "learn list" to expand your horizons. 
Once you see the power of **`Phoenix LiveView`** to create scalable realtime apps with **_minimal_ code** you will see how archaic **`Hapi`** is ... https://github.com/dwyl/phoenix-liveview-counter-tutorial
