### ISSUE TITLE
Add support for 'optional' auth mode

### ISSUE THREAD

**Issue by harriha** [dwyl/hapi-auth-jwt2#43]
Hi,

Not 100% sure if I've managed to grasp Hapi's authentication config model properly, but here we go anyway.

It seems that this plugin doesn't support the authentication mode 'optional' (or 'try'). I'd like to have a route ("/login") configured so that it doesn't enforce authentication but allows it, use case being "if trying to log in when already authenticated, kill the previous session/token, create a new one and let the user continue with that". 

In practice, as far as I can see, the change would be avoiding sending a 401 in case of a missing token if the mode is 'optional'.

Thoughts?

I'm not sure what's the Hapi's overall approach to these modes and how should auth plugins handle them in general, but I'm currently thinking that there might be something to change in Hapi's side as well: to either enforce handling of all these modes (probably not viable) or then make it explicit in all plugins whether they support these modes or not via some kind of contract. Now, based on the Hapi's API docs, I get the impression that I can just adjust this auth mode and things work, no matter what auth method/plugin I was using.

**Comment by eventhough** [comment]
@harriha All this plugin does is check whether or not the token supplied in the request header is valid. If the token is valid it will provide the decoded values for you in `validateFunc`, otherwise it will return a 401. If you want to renew or refresh the user's token you should probably set up a route in hapi to handle this. Something like /auth/refresh which returns a new token if the supplied token is valid.

Another option you could try is storing a session ID in your jwt token and storing the session contents in redis (or some other cache). (If you set `ignoreExpiration` option to true in hapi-auth-jwt it will ignore expiration.) Then you could create another plugin and extend 'onPostAuth' and refresh your session expiration in redis automatically. [server.ext()](http://hapijs.com/api#serverextevent-method-options)

That way whenever a user makes an action this plugin serves as a keepalive for the session. What do you think?

**Comment by harriha** [comment]
Hi @eventhough,

Yep, I understand what the plugin does, I wasn't expecting it to be able to renew the token or do any other kind of magic on its own. My question is whether the plugin could/should comply with the Hapi's route authentication modes (https://github.com/hapijs/hapi/blob/master/API.md#route-options) which would enable my use case. 

That particular use case of mine (renewing a session) can be done in various ways and mimicking that 'optional' behavior via handling the JWT by hand is easy-enough, so it's not a blocker, but would of course be nicer if I could avoid fiddling with the token decoding manually and just configure the route as I wish. And it still might be that I end up redoing the whole thing in a different way, rendering this need obsolete in my case.

I can see that the need for these additional auth modes might not be that common, thus this was more like an open question whether others see any point in this kind of change. As mentioned, it's slightly confusing to see these auth modes mentioned in Hapi docs and find out only by trial-and-error that auth plugins don't support them as one might assume - having said that, not sure if this is more of a problem with plugins themselves, Hapi docs or Hapi's auth plugin architecture. Or just me failing to comprehend the overall architecture :).

**Comment by eventhough** [comment]
@harriha Okay I see what you are saying here. I think we should definitely support those authentication modes.

@nelsonic I've created some additional tests to test each authentication mode but I need to able to see my console.logs when I run these tests. Is there a way I can run tests and print everything? It seems like istanbul is suppressing debug statements.

**Comment by nelsonic** [comment]
@eventhough 
try:
```sh
npm run quick
```
That should print everything to console.

**Comment by harriha** [comment]
@eventhough Ok, cool, thanks. If I can help with this somehow, please let me know.

**Comment by eventhough** [comment]
@harriha Just created a PR #44 to support both `optional` and `try` modes.

**Comment by nelsonic** [comment]
@harriha + @eventhough the latest version has been published to NPM. **4.4.0** has the optional auth mode. 
thanks! :+1:

**Comment by harriha** [comment]
Hey, thanks a lot, that was fast! Cheers!

**Comment by iteles** [comment]
@harriha That's how we roll :wink: @eventhough and @nelsonic are pretty awesome!
