### ISSUE TITLE
Custom errors from validate function?

### ISSUE THREAD

**Issue by harriha** [dwyl/hapi-auth-jwt2#58]
Hi,

I noticed that there's no way to provide a custom error message up from the validate function to the calling client/end user. In my case, had the following scenario:

- I'm doing some validation from DB in the validate function (I'm aware of the potential perf issues, but fine for my case here)
- There was an issue with the DB connection, which ended up failing the validation
  - I'm handing over the error object I got and `false` to the validate function callback
- The client will see HTTP 401 and error message 'Invalid token', which is misleading here. I'd rather send HTTP 500 or similar since the issue wasn't really with authentication.

Any ideas how to improve things here? The error checks [here](https://github.com/dwyl/hapi-auth-jwt2/blob/master/lib/index.js#L74) are quite broad. Would it make sense to allow the use of a pre-defined set of contextual error messages from the validate function and if the err is something else, then give HTTP 500? Not sure if protecting for these kind of error cases is the job for this plugin here, but cannot figure out another way how to hook into this flow earlier and offer better error messages to the calling client.

**Comment by nelsonic** [comment]
@harriha great question!
I would recommend loggin the DB error in your `validateFunc` using Good: https://github.com/hapijs/good
but send a 400 error to the client to avoid leaking information that could be used to crash your application and/or database.
See **API Attacks**: http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c18.pdf

**Comment by harriha** [comment]
Yeah, leaking too much info is a good point, although here the case wasn't the API call causing the issue with DB, it was something else. Moreover, that was just an example, the actual issue with the authentication could be something else (related to domain of the app for example), which would be nice to be seen by the user. But yeah, this is maybe a bit difficult topic to work around, pros and cons with all approaches, and making something like auth validation function more complex than what it really needs to be might be begging for trouble. Maybe I'll see if I can figure out something useful in my end and if it feels helpful-enough, I'll submit a PR for review.

**Comment by jamesdixon** [comment]
@harriha @nelsonic I was just actually looking for similar functionality. In my use case, in the validation function, I'm checking to see if the token exists in Redis. I'm storing the token in Redis so that way it could be invalidated if for some reason the user was past due on their bill or some other reason for disabling their account. If their account is disabled, I would like to display that to the user so that I can avoid having to determine if it's an actual authentication issue or the account is disabled, etc.

That said, what exactly does the `err` param in the callback function signature do? I've tried passing things to it, but not seeing anything in logging or in the API response. Thanks!

**Comment by harriha** [comment]
If I'm not mistaken, #77 closes this one, too - great! @nelsonic, care to confirm please? And feel free to close this one.

**Comment by nelsonic** [comment]
Indeed. well spotted @harriha !
Thanks for being on top of the issues! :+1:
